<div id="not-supported" class="modal hide fade">
    <h3>Browser not supported</h3>
    <p>
        It seems that your web browser does not support some of the 
        technology we're using to make our website rich and dynamic.
    </p>
    <p>
        We encourage you to upgrade to a popular, modern browser and 
        enable automatic updates. 
    </p>
    <ul id="supported-browsers">
        <li>
            <a target="_blank" href="http://www.google.com/chrome/">Chrome</a>
        </li>
        <li>
            <a target="_blank" href="http://www.apple.com/safari/">Safari</a>
        </li>
        <li>
            <a target="_blank" href="http://www.mozilla.org/firefox/">Firefox</a>
        </li>
        <li>
            <a target="_blank" href="http://www.microsoft.com/windows/ie/">Internet Explorer</a>
        </li>
    </ul>
    <p>
        Skip upgrading and <a id="initialize-view" href="#">continue using the website anyway</a>
    </p>
</div>