<div id="place-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <div class="modal-body">
      <img src="{{& bigImg}}" />
    </div>
    <div class="modal-footer">
      <p>
        You'll need our Interface client to visit these domains.<br />
        Check back soon, or enter your email address to be notified.
      </p>
      <p>
        <a href="#subscribe">Notify me</a>
        <a href="{{& url}}">I have Interface</a>
      </p>
    </div>
  </div>
</div>